const getRoutes = {
    "homepage": "/",
    "contact": "/contact",
    "corporate": "/corporate/about-us",
    "about us": "/corporate/about-us",
    "coo's message": "/corporate/coos-message",
    "milestones": "/corporate/milestones",
    "our team": "our-team",
    // "our story": "/corporate/our-story",
    "our vision and values": "/corporate/our-vision-and-values",
    "career": "/career",
    "sustainability": "/sustainability",
    "activity fields": "/activity-fields/industry",
    "generation": "/activity-fields/generation",
    "transmission": "/activity-fields/transmission",
    "distribution": "/activity-fields/distribution",
    "automation": "/activity-fields/automation",
    "automation and control": "/activity-fields/automation-and-control",
    "industry": "/activity-fields/industry",
    "power": "/activity-fields/power",
    "power sector": "/activity-fields/power-sector",
    "engineering services": "/activity-fields/engineering-services",
    "paas / eaas": "/activity-fields/paas-and-eaas",
    "fibre optics": "/activity-fields/fibre-optics",
    "reports": "/safety-mission/reports",
    // "hse policy": "/safety-mission/hse-policy",
    "hse policy": "/sustainability/hse-policy",
    "safe workplace": "/sustainability/safe-workplace",
    "news": "/media-center/news",
    "press releases": "/media-center/press-releases",
    "photo gallery": "/media-center/photo-gallery",
    "video gallery": "/media-center/video-gallery",
    "privacy policy": "/privacy-policy"
}

export default getRoutes